import { Injectable } from '@angular/core';

export interface PdfRevision {
  readonly revisionNumber: number;
  readonly startOffset: number;
  readonly endOffset: number;
  readonly byteLength: number;
  readonly percentageOfTotal: number;
  readonly isInitialCreation: boolean;
  readonly producer?: string;
  readonly creator?: string;
  readonly modificationDate?: Date;
  readonly objectsCount?: number;
}

export interface ForensicAnomaly {
  readonly severity: 'warning' | 'info' | 'danger';
  readonly title: string;
  readonly description: string;
}

export interface ForensicsReport {
  readonly totalFileSize: number;
  readonly revisionCount: number;
  readonly revisions: PdfRevision[];
  readonly anomalies: ForensicAnomaly[];
  readonly isLinearized: boolean;
  readonly pdfVersion: string;
  readonly hasTrailingData: boolean;
  readonly trailingDataBytes: number;
  readonly originalCreationDate?: Date;
  readonly lastModificationDate?: Date;
  readonly summary: string;
}

@Injectable({ providedIn: 'root' })
export class PdfForensicsService {
  /**
   * Analyzes the binary structure of a PDF to reconstruct its incremental revision history
   * and detect forensic anomalies.
   */
  analyzeDocument(bytes: Uint8Array): ForensicsReport {
    if (!bytes || bytes.byteLength === 0) {
      return {
        totalFileSize: 0,
        revisionCount: 0,
        revisions: [],
        anomalies: [],
        isLinearized: false,
        pdfVersion: 'Unknown',
        hasTrailingData: false,
        trailingDataBytes: 0,
        summary: 'Empty document.',
      };
    }

    const latinText = this.bytesToLatin1(bytes);
    const pdfVersion = this.detectPdfVersion(latinText);
    const isLinearized = /\/Linearized\s+1\b/.test(latinText);

    // Find all %%EOF positions
    const eofOffsets = this.findAllEofOffsets(bytes, latinText);
    const revisionCount = Math.max(1, eofOffsets.length);

    const revisions: PdfRevision[] = [];
    let prevEnd = 0;

    for (let i = 0; i < eofOffsets.length; i++) {
      const eofEnd = eofOffsets[i];
      const start = i === 0 ? 0 : prevEnd;
      const length = eofEnd - start;
      const percentage = (length / bytes.byteLength) * 100;

      const chunkText = latinText.substring(start, eofEnd);
      const producer = this.extractRegex(chunkText, /\/Producer\s*\(([^)]+)\)/);
      const creator = this.extractRegex(chunkText, /\/Creator\s*\(([^)]+)\)/);
      const modDate = this.extractPdfDate(chunkText, '/ModDate') ?? (i === 0 ? this.extractPdfDate(chunkText, '/CreationDate') : undefined);
      const objectsCount = this.estimateObjectCount(chunkText);

      revisions.push({
        revisionNumber: i + 1,
        startOffset: start,
        endOffset: eofEnd,
        byteLength: length,
        percentageOfTotal: Math.round(percentage * 10) / 10,
        isInitialCreation: i === 0,
        producer,
        creator,
        modificationDate: modDate,
        objectsCount,
      });

      prevEnd = eofEnd;
    }

    const lastEof = eofOffsets.length > 0 ? eofOffsets[eofOffsets.length - 1] : bytes.byteLength;
    const trailingDataBytes = Math.max(0, bytes.byteLength - lastEof);
    const hasTrailingData = trailingDataBytes > 8; // small tolerance for trailing newlines

    // Detect anomalies
    const anomalies: ForensicAnomaly[] = [];

    if (revisionCount > 1) {
      anomalies.push({
        severity: 'info',
        title: 'Incremental Updates Detected',
        description: `This PDF contains ${revisionCount} revision(s). It was edited and saved ${revisionCount - 1} time(s) after initial generation.`,
      });
    }

    if (hasTrailingData) {
      anomalies.push({
        severity: 'warning',
        title: 'Trailing Unreferenced Data',
        description: `Found ${trailingDataBytes} bytes after the final %%EOF marker. This can indicate appended data or file corruption.`,
      });
    }

    const initialRev = revisions[0];
    const latestRev = revisions[revisions.length - 1];

    if (initialRev?.producer && latestRev?.producer && initialRev.producer !== latestRev.producer) {
      anomalies.push({
        severity: 'warning',
        title: 'Producer Mismatch Across Revisions',
        description: `Originally generated by "${initialRev.producer}", but subsequent revision was modified by "${latestRev.producer}".`,
      });
    }

    const creationDate = this.extractPdfDate(latinText, '/CreationDate');
    const modDate = this.extractPdfDate(latinText, '/ModDate');

    if (creationDate && modDate && modDate.getTime() < creationDate.getTime()) {
      anomalies.push({
        severity: 'danger',
        title: 'Inconsistent Date Timeline',
        description: 'The modification timestamp is older than the creation timestamp, which may indicate altered metadata.',
      });
    }

    let summary = 'Standard single-revision document with no detected anomalies.';
    if (revisionCount > 1) {
      summary = `Document has undergone ${revisionCount - 1} incremental update(s). Previous revisions can be inspected or rolled back.`;
    }

    return {
      totalFileSize: bytes.byteLength,
      revisionCount,
      revisions,
      anomalies,
      isLinearized,
      pdfVersion,
      hasTrailingData,
      trailingDataBytes,
      originalCreationDate: creationDate,
      lastModificationDate: modDate,
      summary,
    };
  }

  /**
   * Slices the PDF to extract only Revision 1 (the original version before any incremental edits).
   */
  extractOriginalRevision(bytes: Uint8Array): Uint8Array | null {
    return this.extractRevision(bytes, 1);
  }

  /**
   * Slices the PDF to extract a specific incremental revision (1-indexed).
   */
  extractRevision(bytes: Uint8Array, revisionNumber: number): Uint8Array | null {
    const latinText = this.bytesToLatin1(bytes);
    const eofOffsets = this.findAllEofOffsets(bytes, latinText);
    if (revisionNumber <= 0 || revisionNumber > eofOffsets.length) {
      return null;
    }

    const targetEof = eofOffsets[revisionNumber - 1];
    return bytes.slice(0, targetEof);
  }

  private findAllEofOffsets(bytes: Uint8Array, latinText: string): number[] {
    const offsets: number[] = [];
    const regex = /%%EOF/g;
    let match: RegExpExecArray | null;

    while ((match = regex.exec(latinText)) !== null) {
      // Validate proximity to startxref within ~256 bytes to prevent false matches inside binary streams
      const windowBefore = latinText.substring(Math.max(0, match.index - 256), match.index);
      if (!/startxref[\s\S]{1,200}$/i.test(windowBefore)) {
        // If not preceded by startxref, skip (likely an uncompressed stream match)
        continue;
      }

      let end = match.index + 5;
      // Skip trailing CR/LF
      while (end < bytes.byteLength && (bytes[end] === 10 || bytes[end] === 13)) {
        end++;
      }
      offsets.push(end);
    }

    // Fallback: If strict startxref search found nothing, capture all %%EOF
    if (offsets.length === 0) {
      regex.lastIndex = 0;
      while ((match = regex.exec(latinText)) !== null) {
        let end = match.index + 5;
        while (end < bytes.byteLength && (bytes[end] === 10 || bytes[end] === 13)) {
          end++;
        }
        offsets.push(end);
      }
    }

    // Final fallback if no %%EOF found at all
    if (offsets.length === 0) {
      offsets.push(bytes.byteLength);
    }

    return offsets;
  }

  private detectPdfVersion(latinText: string): string {
    const catalogMatch = /\/Version\s*\/(\d+\.\d+)/.exec(latinText);
    if (catalogMatch) {
      return `PDF ${catalogMatch[1]}`;
    }
    const match = /%PDF-(\d+\.\d+)/.exec(latinText);
    return match ? `PDF ${match[1]}` : 'PDF (Standard)';
  }

  private extractRegex(text: string, regex: RegExp): string | undefined {
    const match = regex.exec(text);
    return match ? match[1] : undefined;
  }

  private extractPdfDate(text: string, key: string): Date | undefined {
    const regex = new RegExp(`${key}\\s*\\((?:D:)?(\\d{4})(\\d{2})?(\\d{2})?(\\d{2})?(\\d{2})?(\\d{2})?`);
    const match = regex.exec(text);
    if (!match) return undefined;

    const year = parseInt(match[1], 10);
    const month = match[2] ? parseInt(match[2], 10) - 1 : 0;
    const day = match[3] ? parseInt(match[3], 10) : 1;
    const hour = match[4] ? parseInt(match[4], 10) : 0;
    const min = match[5] ? parseInt(match[5], 10) : 0;
    const sec = match[6] ? parseInt(match[6], 10) : 0;

    return new Date(Date.UTC(year, month, day, hour, min, sec));
  }

  private estimateObjectCount(text: string): number {
    const matches = text.match(/\b\d+\s+\d+\s+obj\b/g);
    return matches ? matches.length : 0;
  }

  private bytesToLatin1(bytes: Uint8Array): string {
    let result = '';
    const chunk = 8192;
    for (let i = 0; i < bytes.length; i += chunk) {
      result += String.fromCharCode(...bytes.subarray(i, Math.min(i + chunk, bytes.length)));
    }
    return result;
  }
}
