/**
 * font-subset-analyzer.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Prompt 2 Spike — Embedded Subset Font Glyph Analysis
 *
 * Parses an embedded font program from a PDF using fontkit to enumerate:
 *   - Which Unicode code points are available in the font subset.
 *   - The PDF encoding used by the font (Simple / CIDFont / ToUnicode cmap).
 *   - How to map new text characters to the correct byte codes for the PDF
 *     content stream (the "encoding problem" from PRD §7).
 *
 * PRD §7 — "Custom/non-standard character encodings on embedded fonts require
 * mapping new characters to the correct glyph codes, not just raw text — this
 * is the single hardest technical piece of v1."
 *
 * PRD §13 Q1 resolution → Decision: BLOCK the character (Option A) for v1.
 * Rationale: Simpler, safer, avoids silent corruption. See DECISION block below.
 *
 * IMPORTANT: Zero Angular imports. Framework-agnostic module.
 *
 * ── ENCODING STRATEGIES HANDLED ─────────────────────────────────────────────
 *
 * 1. Simple (single-byte) fonts with /Encoding + /ToUnicode:
 *    - /ToUnicode CMap stream maps byte codes (0x00–0xFF) → Unicode.
 *    - Reverse map: Unicode char → byte code.
 *    - fontkit confirms the glyph exists in the embedded program.
 *
 * 2. CIDFont (composite / Type0) with /ToUnicode:
 *    - /ToUnicode maps 2-byte char codes → Unicode.
 *    - Reverse map: Unicode char → 2-byte code.
 *    - Content stream uses multi-byte strings.
 *
 * 3. No /ToUnicode (fallback):
 *    - Attempt /Encoding dict (Standard, MacRoman, WinAnsi, custom).
 *    - If unavailable, treat as WinAnsi and report limitation.
 *
 * ── MISSING GLYPH DECISION (PRD §13 Q1) ─────────────────────────────────────
 *
 * OPTION A — Block the character (CHOSEN for v1):
 *   When a character the user types is not in the embedded subset, we prevent
 *   the keystroke and show a toast warning. No content-stream mutation occurs.
 *   Rationale: Zero risk of silent corruption; implementation straightforward;
 *   consistent with "one style per run" simplification (PRD §13 Q2).
 *
 * OPTION B — Fallback font for the run (rejected for v1):
 *   Replace the entire run's font with a matched system font.
 *   Rejected because: (a) requires reliable system font matching table,
 *   (b) visual appearance changes (different metrics), (c) introduces
 *   a new font resource in the PDF which breaks the "same resource" guarantee.
 *
 * ────────────────────────────────────────────────────────────────────────────
 */

import type { GlyphValidationResult } from './text-run.model';

// ─── fontkit Types (lightweight import) ──────────────────────────────────────
// fontkit uses CommonJS and works in-browser via the browser bundle.
// We type-import only what we need to stay framework-agnostic.

type FontkitFont = {
  characterSet: number[];
  hasGlyphForCodePoint(codePoint: number): boolean;
  glyphForCodePoint(codePoint: number): { id: number; codePoints: number[] };
  postscriptName: string | null;
  numGlyphs: number;
};

// ─── ToUnicode CMap Parser ────────────────────────────────────────────────────

/**
 * Parses a PDF ToUnicode CMap stream into two maps:
 *   - byteToUnicode: charCode → unicode string
 *   - unicodeToByte: unicode string → charCode
 *
 * Handles both bfchar (single character mappings) and bfrange sections.
 * This covers virtually all real-world PDFs generated by modern tools.
 */
export interface ToUnicodeMap {
  /** charCode (number) → Unicode string. For simple fonts: 0–255. For CIDFonts: 0–65535. */
  byteToUnicode: Map<number, string>;
  /** Unicode string → charCode. Used to encode new text. */
  unicodeToByte: Map<string, number>;
  /** true = 2-byte char codes (CIDFont/composite); false = 1-byte (simple font). */
  isTwoByteEncoding: boolean;
}

export function parseToUnicodeCMap(cmapText: string): ToUnicodeMap {
  const byteToUnicode = new Map<number, string>();
  const unicodeToByte = new Map<string, number>();
  let isTwoByteEncoding = false;

  // Detect if this is a two-byte encoding by looking at the codespacerange.
  const codespaceMatch = /begincodespacerange\s+([\s\S]*?)endcodespacerange/.exec(cmapText);
  if (codespaceMatch) {
    // If the range bounds are 4 hex digits (e.g. <0000> <FFFF>), it's two-byte.
    const rangeText = codespaceMatch[1].trim();
    isTwoByteEncoding = /<[0-9a-fA-F]{4}>/.test(rangeText);
  }

  // Parse bfchar sections: <srcCode> <dstUnicode>
  const bfcharRegex = /beginbfchar\s*([\s\S]*?)endbfchar/g;
  let bfcharMatch: RegExpExecArray | null;
  while ((bfcharMatch = bfcharRegex.exec(cmapText)) !== null) {
    const lines = bfcharMatch[1].split('\n');
    for (const line of lines) {
      const m = /^<([0-9a-fA-F]+)>\s+<([0-9a-fA-F]+)>/.exec(line.trim());
      if (!m) continue;
      const charCode = parseInt(m[1], 16);
      const unicodeHex = m[2];
      // Unicode hex may be 4 digits (BMP) or 8 digits (supplementary).
      const unicode = hexToUnicodeString(unicodeHex);
      byteToUnicode.set(charCode, unicode);
      // Only map the first occurrence (subset may have duplicates).
      if (!unicodeToByte.has(unicode)) {
        unicodeToByte.set(unicode, charCode);
      }
    }
  }

  // Parse bfrange sections: <startCode> <endCode> <startUnicode>
  const bfrangeRegex = /beginbfrange\s*([\s\S]*?)endbfrange/g;
  let bfrangeMatch: RegExpExecArray | null;
  while ((bfrangeMatch = bfrangeRegex.exec(cmapText)) !== null) {
    const lines = bfrangeMatch[1].split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      // Array form: <start> <end> [<u1> <u2> ...]
      const arrayMatch = /^<([0-9a-fA-F]+)>\s+<([0-9a-fA-F]+)>\s+\[/.exec(trimmed);
      if (arrayMatch) {
        const start = parseInt(arrayMatch[1], 16);
        const end = parseInt(arrayMatch[2], 16);
        const vals = [...trimmed.matchAll(/<([0-9a-fA-F]+)>/g)].slice(2);
        for (let i = 0; i <= end - start && i < vals.length; i++) {
          const charCode = start + i;
          const unicode = hexToUnicodeString(vals[i][1]);
          byteToUnicode.set(charCode, unicode);
          if (!unicodeToByte.has(unicode)) unicodeToByte.set(unicode, charCode);
        }
        continue;
      }
      // Linear range: <start> <end> <startUnicode>
      const rangeMatch = /^<([0-9a-fA-F]+)>\s+<([0-9a-fA-F]+)>\s+<([0-9a-fA-F]+)>/.exec(trimmed);
      if (!rangeMatch) continue;
      const start = parseInt(rangeMatch[1], 16);
      const end = parseInt(rangeMatch[2], 16);
      const uStart = parseInt(rangeMatch[3], 16);
      for (let i = 0; i <= end - start; i++) {
        const charCode = start + i;
        const unicode = String.fromCodePoint(uStart + i);
        byteToUnicode.set(charCode, unicode);
        if (!unicodeToByte.has(unicode)) unicodeToByte.set(unicode, charCode);
      }
    }
  }

  return { byteToUnicode, unicodeToByte, isTwoByteEncoding };
}

function hexToUnicodeString(hex: string): string {
  // Handles both 4-digit BMP and 8-digit surrogate pairs.
  if (hex.length <= 4) {
    return String.fromCodePoint(parseInt(hex, 16));
  }
  // 8+ digits: split into pairs, interpret as UTF-16 code units.
  let result = '';
  for (let i = 0; i < hex.length; i += 4) {
    const unit = parseInt(hex.slice(i, i + 4), 16);
    result += String.fromCharCode(unit);
  }
  return result;
}

// ─── Font Subset Analysis Result ─────────────────────────────────────────────

export interface FontSubsetInfo {
  /** PDF font resource key (e.g. "F1"). */
  fontKey: string;

  /** PostScript/family name as reported by fontkit. */
  postscriptName: string;

  /** Number of glyphs in the embedded font program. */
  numGlyphs: number;

  /**
   * Set of Unicode code points available in this font subset.
   * Populated from fontkit's characterSet (which reads the cmap table).
   */
  availableCodePoints: ReadonlySet<number>;

  /**
   * Set of Unicode strings (characters) available in this font subset.
   * Derived from availableCodePoints. Use this for UI validation.
   */
  availableChars: ReadonlySet<string>;

  /**
   * ToUnicode mapping for this font (if present in the PDF).
   * Used to encode text back to byte codes for the content stream.
   */
  toUnicodeMap: ToUnicodeMap | null;

  /**
   * Font type: Simple (single-byte) or Composite/CIDFont (multi-byte).
   * Determines how to encode strings in the Tj/TJ operator.
   */
  fontType: 'simple' | 'composite' | 'type1' | 'unknown';

  /**
   * Whether the font program was successfully parsed by fontkit.
   * If false, glyph availability can only be determined from ToUnicode map.
   */
  fontkitParsed: boolean;

  /** Any warnings encountered during analysis (non-fatal). */
  warnings: string[];
}

// ─── Main Analyzer ───────────────────────────────────────────────────────────

/**
 * Analyzes the embedded font programs for all fonts on a single page.
 *
 * @param pdfBytes - Raw PDF bytes.
 * @param pageIndex - 0-based page index.
 * @returns Map of font resource key → FontSubsetInfo.
 */
export async function analyzeFontsOnPage(
  pdfBytes: Uint8Array | ArrayBuffer,
  pageIndex: number,
): Promise<Map<string, FontSubsetInfo>> {
  const { PDFDocument, PDFName, PDFDict, PDFRawStream, decodePDFRawStream } = await import('pdf-lib');
  const fontkit = await loadFontkit();

  const bytes = pdfBytes instanceof Uint8Array ? pdfBytes : new Uint8Array(pdfBytes);
  const pdfDoc = await PDFDocument.load(bytes, { ignoreEncryption: true });

  const results = new Map<string, FontSubsetInfo>();
  const pages = pdfDoc.getPages();

  if (pageIndex >= pages.length) {
    throw new RangeError(`pageIndex ${pageIndex} out of range [0, ${pages.length - 1}]`);
  }

  const page = pages[pageIndex];
  // Access raw PDF page node to traverse Resources/Font dictionary.
  const pageNode = page.node;

  // Get the Resources dict (may be inherited from parent page tree).
  const resourcesObj = pageNode.lookup(PDFName.of('Resources'));
  if (!resourcesObj || !(resourcesObj instanceof PDFDict)) {
    return results; // No resources on this page.
  }

  const fontDictObj = resourcesObj.lookup(PDFName.of('Font'));
  if (!fontDictObj || !(fontDictObj instanceof PDFDict)) {
    return results; // No fonts on this page.
  }

  // Iterate all font resource entries.
  for (const [fontKeyName, fontRef] of fontDictObj.entries()) {
    const fontKey = fontKeyName.asString();
    const warnings: string[] = [];

    try {
      const fontDict = pdfDoc.context.lookup(fontRef);
      if (!fontDict || !(fontDict instanceof PDFDict)) continue;

      // Determine font type from /Subtype.
      const subtypeObj = fontDict.lookup(PDFName.of('Subtype'));
      const subtype = subtypeObj ? subtypeObj.toString().replace('/', '') : 'Unknown';
      let fontType: FontSubsetInfo['fontType'] = 'unknown';
      if (subtype === 'Type1' || subtype === 'MMType1') fontType = 'type1';
      else if (subtype === 'TrueType' || subtype === 'Type3') fontType = 'simple';
      else if (subtype === 'Type0') fontType = 'composite';
      else if (subtype === 'CIDFontType0' || subtype === 'CIDFontType2') fontType = 'composite';
      else fontType = 'simple'; // Treat unknown as simple for safety.

      // ── Parse ToUnicode CMap ──────────────────────────────────────────────
      let toUnicodeMap: ToUnicodeMap | null = null;
      const toUnicodeRef = fontDict.lookup(PDFName.of('ToUnicode'));
      if (toUnicodeRef instanceof PDFRawStream) {
        const cmapBytes = decodePDFRawStream(toUnicodeRef).decode();
        const cmapText = new TextDecoder().decode(cmapBytes);
        toUnicodeMap = parseToUnicodeCMap(cmapText);
      } else if (toUnicodeRef) {
        // May be an indirect reference — try to resolve it.
        const resolved = pdfDoc.context.lookup(toUnicodeRef);
        if (resolved instanceof PDFRawStream) {
          const cmapBytes = decodePDFRawStream(resolved).decode();
          const cmapText = new TextDecoder().decode(cmapBytes);
          toUnicodeMap = parseToUnicodeCMap(cmapText);
        }
      }

      // ── Extract embedded font program bytes ───────────────────────────────
      let fontProgramBytes: Uint8Array | null = null;
      let fontkitFont: FontkitFont | null = null;

      const descriptorRef = fontDict.lookup(PDFName.of('FontDescriptor'));
      if (descriptorRef instanceof PDFDict) {
        fontProgramBytes = extractFontProgram(descriptorRef, pdfDoc.context, decodePDFRawStream, PDFName, PDFRawStream, warnings);
      } else if (descriptorRef) {
        const resolvedDesc = pdfDoc.context.lookup(descriptorRef);
        if (resolvedDesc instanceof PDFDict) {
          fontProgramBytes = extractFontProgram(resolvedDesc, pdfDoc.context, decodePDFRawStream, PDFName, PDFRawStream, warnings);
        }
      }

      // For composite (Type0) fonts, also check descendant fonts.
      if (!fontProgramBytes && fontType === 'composite') {
        fontProgramBytes = extractCompositeDescendantFont(fontDict, pdfDoc.context, decodePDFRawStream, PDFName, PDFDict, PDFRawStream, warnings);
      }

      // ── Parse with fontkit ────────────────────────────────────────────────
      let fontkitParsed = false;
      let availableCodePoints = new Set<number>();

      if (fontProgramBytes && fontProgramBytes.length > 0) {
        try {
          const fkFont = fontkit.create(fontProgramBytes) as FontkitFont;
          fontkitFont = fkFont;
          fontkitParsed = true;
          // fontkit's characterSet gives all Unicode codepoints the font can render.
          availableCodePoints = new Set(fkFont.characterSet);
        } catch (e) {
          warnings.push(`fontkit parse failed for ${fontKey}: ${String(e)}`);
        }
      }

      // Fall back to ToUnicode map if fontkit parsing failed.
      if (!fontkitParsed && toUnicodeMap) {
        for (const codePoint of toUnicodeMap.unicodeToByte.keys()) {
          for (const cp of [...codePoint].map((c) => c.codePointAt(0)!)) {
            availableCodePoints.add(cp);
          }
        }
        warnings.push(`${fontKey}: Used ToUnicode map as fallback (fontkit not available or parse failed).`);
      }

      // Build Unicode chars set for easy UI validation.
      const availableChars = new Set<string>();
      for (const cp of availableCodePoints) {
        availableChars.add(String.fromCodePoint(cp));
      }
      // Common whitespace characters never require special subset glyphs in PDF
      availableChars.add(' ');
      availableChars.add('\t');
      availableChars.add('\u00A0');

      results.set(fontKey, {
        fontKey,
        postscriptName: fontkitFont?.postscriptName ?? fontKey,
        numGlyphs: fontkitFont?.numGlyphs ?? availableCodePoints.size,
        availableCodePoints,
        availableChars,
        toUnicodeMap,
        fontType,
        fontkitParsed,
        warnings,
      });
    } catch (e) {
      // Non-fatal: skip this font entry with a warning.
      console.warn(`[FontSubsetAnalyzer] Failed to analyze font ${fontKey}:`, e);
    }
  }

  return results;
}

// ─── Internal Helpers ─────────────────────────────────────────────────────────

/** Extracts the raw font program bytes from a FontDescriptor dict. */
function extractFontProgram(
  descriptor: import('pdf-lib').PDFDict,
  context: import('pdf-lib').PDFContext,
  decodePDFRawStream: (s: import('pdf-lib').PDFRawStream) => { decode(): Uint8Array },
  PDFName: typeof import('pdf-lib').PDFName,
  PDFRawStream: typeof import('pdf-lib').PDFRawStream,
  warnings: string[],
): Uint8Array | null {
  // Try FontFile2 (TrueType), then FontFile3 (CFF/OTF), then FontFile (Type1 PFB).
  for (const key of ['FontFile2', 'FontFile3', 'FontFile']) {
    const ref = descriptor.lookup(PDFName.of(key));
    if (!ref) continue;
    const stream = ref instanceof PDFRawStream ? ref : context.lookup(ref);
    if (stream instanceof PDFRawStream) {
      try {
        return decodePDFRawStream(stream).decode();
      } catch (e) {
        warnings.push(`Failed to decode ${key}: ${String(e)}`);
      }
    }
  }
  return null;
}

/** For Type0 (composite) fonts, descend into the DescendantFonts array. */
function extractCompositeDescendantFont(
  fontDict: import('pdf-lib').PDFDict,
  context: import('pdf-lib').PDFContext,
  decodePDFRawStream: (s: import('pdf-lib').PDFRawStream) => { decode(): Uint8Array },
  PDFName: typeof import('pdf-lib').PDFName,
  PDFDict: typeof import('pdf-lib').PDFDict,
  PDFRawStream: typeof import('pdf-lib').PDFRawStream,
  warnings: string[],
): Uint8Array | null {
  const descendantsRef = fontDict.lookup(PDFName.of('DescendantFonts'));
  if (!descendantsRef) return null;
  const descendants = context.lookup(descendantsRef);
  if (!descendants) return null;

  // DescendantFonts is an array of one CIDFont dict.
  const descendantRef = (descendants as import('pdf-lib').PDFArray).get(0);
  if (!descendantRef) return null;
  const cidFontDict = context.lookup(descendantRef);
  if (!(cidFontDict instanceof PDFDict)) return null;

  const descriptorRef = cidFontDict.lookup(PDFName.of('FontDescriptor'));
  if (!descriptorRef) return null;
  const descriptor = context.lookup(descriptorRef);
  if (!(descriptor instanceof PDFDict)) return null;

  return extractFontProgram(descriptor, context, decodePDFRawStream, PDFName, PDFRawStream, warnings);
}

// ─── fontkit Loader ───────────────────────────────────────────────────────────

let _fontkit: { create(buffer: Uint8Array): FontkitFont } | null = null;

async function loadFontkit(): Promise<{ create(buffer: Uint8Array): FontkitFont }> {
  if (_fontkit) return _fontkit;
  // fontkit exports its API directly. Use unknown cast to handle
  // both CJS default-wrapped and ESM direct-export builds.
  const mod = await import('fontkit');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  _fontkit = (mod as unknown as { create(buffer: Uint8Array): FontkitFont });
  return _fontkit;
}

// ─── Validate Glyph Availability (standalone helper) ─────────────────────────

/**
 * Checks whether all characters in `text` can be encoded using the given
 * FontSubsetInfo. Returns a GlyphValidationResult.
 *
 * This is a standalone helper callable without the full engine context.
 * Used by font-glyph-resolver.ts and the Angular UI keystroke interceptor.
 */
export function validateTextAgainstSubset(
  text: string,
  subsetInfo: FontSubsetInfo,
): GlyphValidationResult {
  const missingChars: string[] = [];

  for (const char of text) {
    const codePoint = char.codePointAt(0)!;

    // Check via ToUnicode map first (authoritative for content stream encoding).
    if (subsetInfo.toUnicodeMap) {
      if (!subsetInfo.toUnicodeMap.unicodeToByte.has(char)) {
        missingChars.push(char);
      }
      continue;
    }

    // Fall back to fontkit characterSet.
    if (!subsetInfo.availableCodePoints.has(codePoint)) {
      missingChars.push(char);
    }
  }

  return {
    valid: missingChars.length === 0,
    missingChars,
  };
}

/**
 * Encodes a Unicode string to the byte sequence expected in the PDF content
 * stream for a given font.
 *
 * For simple fonts: returns a Uint8Array of single-byte char codes.
 * For composite fonts: returns a Uint8Array of 2-byte char codes (big-endian).
 *
 * Returns null if any character cannot be encoded (missing from subset).
 * The caller must validate first with validateTextAgainstSubset().
 */
export function encodeTextForContentStream(
  text: string,
  subsetInfo: FontSubsetInfo,
): Uint8Array | null {
  if (!subsetInfo.toUnicodeMap) {
    // Without a ToUnicode map we can't reliably encode — return null.
    return null;
  }

  const { unicodeToByte, isTwoByteEncoding } = subsetInfo.toUnicodeMap;
  const bytes: number[] = [];

  for (const char of text) {
    let code = unicodeToByte.get(char);
    if (code === undefined && (char === ' ' || char === '\u00A0')) {
      code = isTwoByteEncoding ? 0x0020 : 0x20;
    }
    if (code === undefined) return null; // Missing glyph — caller should have blocked.

    if (isTwoByteEncoding) {
      bytes.push((code >> 8) & 0xff); // High byte.
      bytes.push(code & 0xff);         // Low byte.
    } else {
      bytes.push(code & 0xff);
    }
  }

  return new Uint8Array(bytes);
}
